// FPS Booster Pro - String table (English + Persian)
#pragma once

enum StrId {
    SID_APP_NAME = 0,
    SID_APP_TAG,
    SID_ADMIN_OK,
    SID_ADMIN_NO,
    // Navigation
    SID_NAV_DASH,
    SID_NAV_GAMES,
    SID_NAV_BOOST,
    SID_NAV_TWEAKS,
    SID_NAV_SYSTEM,
    SID_NAV_HELP,
    SID_NAV_SETTINGS,
    // Common
    SID_ON, SID_OFF, SID_YES, SID_NO,
    SID_APPLIED, SID_NOT_APPLIED, SID_NA, SID_ACTION_NEEDED,
    SID_RECOMMENDED, SID_ADVANCED, SID_NEEDS_REBOOT,
    SID_BTN_APPLY, SID_BTN_REVERT, SID_BTN_APPLY_ALL, SID_BTN_REVERT_ALL,
    SID_BTN_REFRESH, SID_BTN_CLOSE, SID_BTN_BROWSE, SID_BTN_ADD,
    SID_BTN_REMOVE, SID_BTN_SAVE, SID_BTN_CANCEL,
    SID_STATUS_READY, SID_VER,
    // Dashboard
    SID_DASH_TITLE, SID_DASH_SUB,
    SID_DASH_SCORE, SID_DASH_GRADE,
    SID_DASH_SYSTEM, SID_DASH_CPU, SID_DASH_GPU, SID_DASH_RAM,
    SID_DASH_OS, SID_DASH_POWER, SID_DASH_DISPLAY,
    SID_DASH_STATUS, SID_DASH_BOOST, SID_DASH_TIP,
    SID_DASH_GAMES, SID_DASH_LASTBOOST, SID_DASH_NEVER,
    SID_TIP1, SID_TIP2, SID_TIP3, SID_TIP4, SID_TIP5,
    // Games
    SID_G_TITLE, SID_G_SUB,
    SID_G_COL_NAME, SID_G_COL_PATH, SID_G_COL_PLAYS, SID_G_COL_LAST,
    SID_G_ADD, SID_G_SCAN, SID_G_REMOVE, SID_G_SETTINGS,
    SID_G_PRIORITY, SID_G_PRIO0, SID_G_PRIO1, SID_G_PRIO2,
    SID_G_AFFINITY, SID_G_AFF0, SID_G_AFF1,
    SID_G_GPUPREF, SID_G_FSO, SID_G_ARGS,
    SID_G_TIMER, SID_G_POWER, SID_G_KILL,
    SID_G_LAUNCH, SID_G_IDLE, SID_G_PREP, SID_G_RUNNING, SID_G_DONE,
    SID_G_EMPTY, SID_G_ADDED, SID_G_PICK_EXE, SID_G_EXE_FILTER,
    SID_G_SCAN_DONE, SID_G_NO_NEW, SID_G_TIP_TITLE, SID_G_KILL_HINT,
    // Boost
    SID_B_TITLE, SID_B_SUB,
    SID_B_START, SID_B_UNDO, SID_B_WORKING, SID_B_DONE, SID_B_FAIL,
    SID_B_STEP_RESTORE, SID_B_STEP_BACKUP, SID_B_STEP_TWEAKS,
    SID_B_STEP_TEMP, SID_B_STEP_RAM, SID_B_STEP_DISP, SID_B_STEP_SCORE,
    SID_B_REBOOT_MSG, SID_B_CONFIRM_UNDO,
    // Tweaks
    SID_T_TITLE, SID_T_SUB,
    SID_T_COL_NAME, SID_T_COL_STATUS, SID_T_COL_CAT,
    SID_T_CAT_GAMING, SID_T_CAT_PERF, SID_T_CAT_VISUAL,
    SID_T_CAT_NET, SID_T_CAT_PRIV, SID_T_CAT_ADV, SID_T_CAT_ACT,
    SID_T_APPLY, SID_T_REVERT, SID_T_ALL, SID_T_UNDO_ALL, SID_T_DETAIL,
    SID_T_WARN,
    // System
    SID_S_TITLE, SID_S_SUB,
    SID_S_CPU, SID_S_RAM, SID_S_UPTIME, SID_S_TIMER,
    SID_S_CLEAN_RAM, SID_S_CLEAN_TEMP, SID_S_MAXREFRESH,
    SID_S_FREED, SID_S_REFRESH_DONE, SID_S_REFRESH_NONE,
    // Help
    SID_H_TITLE, SID_H_SUB, SID_H_TEXT,
    // Settings
    SID_SET_TITLE, SID_SET_SUB,
    SID_SET_LANG, SID_SET_LANG_EN, SID_SET_LANG_FA,
    SID_SET_TRAY, SID_SET_STARTUP, SID_SET_FOLDER,
    SID_SET_RESET, SID_SET_ABOUT,
    SID_SET_CONFIRM_RESET, SID_SET_RESTART_LANG,
    // Messages
    SID_MSG_ADMIN, SID_MSG_DONE, SID_MSG_FAIL, SID_MSG_ERROR,
    SID_MSG_REBOOT_NOW, SID_MSG_NEED_ADMIN,
    SID_TRAY_OPEN, SID_TRAY_BOOST, SID_TRAY_EXIT, SID_TRAY_TIP,
    SID_NAV_POWER,
    SID_P_SUB, SID_P_CUR, SID_P_BEAST, SID_P_ACTIVE, SID_P_OFF,
    SID_P_ACTIVATE, SID_P_DEACTIVATE,
    SID_P_COL_SET, SID_P_COL_BEAST, SID_P_COL_CUR,
    SID_P_APPLYALL, SID_P_RESTORE, SID_P_DELETE,
    SID_P_NOTE, SID_P_APPLIED, SID_P_NEVER,
    SID_NAV_NET,
    SID_N_SUB, SID_N_PING, SID_N_DOWN, SID_N_UP, SID_N_IP, SID_N_START, SID_N_CANCEL,
    SID_N_TESTING, SID_N_GRADE, SID_N_GR0, SID_N_GR1, SID_N_GR2, SID_N_GR3,
    SID_N_SERVER, SID_N_DNS_T, SID_N_DNS_CUR, SID_N_DNS_CF, SID_N_DNS_GOOG, SID_N_DNS_AUTO, SID_N_ERR,
    SID_G_AUTO, SID_G_AUTO_WATCH, SID_G_AUTO_BOOST,
    SID_S_RES, SID_S_RES_APPLY, SID_S_RES_NATIVE,
    SID_B_MAXFPS, SID_B_MAXFPS_WARN, SID_M_SVC, SID_M_BEAST, SID_M_TIMER, SID_M_KILL, SID_M_RES,
    SID_N_DNS_PING, SID_N_DNS_FASTEST, SID_N_DNS_CUSTOM, SID_N_DNS_SET, SID_N_DNS_Q9,
    SID_N_DNS_ODNS, SID_N_DNS_SHECAN, SID_N_DNS_CUSTOMITEM, SID_N_PINGING,
    SID_SET_STARTUP_T, SID_SET_ST_COL1, SID_SET_ST_COL2, SID_SET_ST_ENABLE,
    SID_SET_ST_DISABLE, SID_ST_ON, SID_ST_OFF,
    SID_S_GPU, SID_S_COPY, SID_S_COPIED,
    SID_NAV_PROC,
    SID_R_TITLE, SID_R_SUB, SID_R_COL_PROC, SID_R_COL_PID, SID_R_COL_RAM, SID_R_COL_GAME,
    SID_R_BOOST, SID_R_RAMFOCUS, SID_R_RESTORE, SID_R_HINT, SID_R_SELF,
    SID_M_GAME,
    SID_SET_THEME, SID_SET_THEME_DARK, SID_SET_THEME_LIGHT, SID_SET_THEME_AUTO,
    SID_SET_ACCENT, SID_SET_ACC0, SID_SET_ACC1, SID_SET_ACC2, SID_SET_ACC3,
    SID_SET_HOTKEY, SID_SET_UPDATE,
    SID_UPD_LATEST, SID_UPD_NEW, SID_UPD_FAIL,
    SID_R_LOCK, SID_R_MAXMB, SID_R_ADD, SID_R_KILL, SID_R_KILLCF,
    SID_G_RESCHK, SID_G_RESKEEP,
    SID_COUNT
};

void    Strings_Init();
void    Strings_SetLang(int lang); // 0 = English, 1 = Persian
int     Strings_GetLang();
const wchar_t* T(StrId id);
